# Configuration Settings for M8N device

debug: 4                    # Range 0-4 (0 means no debug statements will print)
                            # 4: show raw ub and nmea msgs RX+TX
                            # 2: show raw ub and nmea msgs TX

save:
  mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver 
                            # Manager, Antenna, and Logging Configuration
  device: 4                 # Save to EEPROM

device: /dev/ttyACM0
frame_id: jetbot
rate: 4                     # in Hz
nav_rate: 4                 # [# of measurement cycles], recommended 1 Hz, may 
                            # be either 5 Hz (Dual constellation) or 
                            # 8 Hz (GPS only)
dynamic_model: pedestrian   # Airborne < 2G, 2D fix not supported (3D only), 
                            # 0: portable, <= 310 m/s, general purpose, low position accuracy
                            # 2: stationary, 0 m/s
                            # 3: pedestrian, <=  30 m/s
                            # 4: automotive, <= 100 m/s
                            # Max Alt: 50km
                            # Max Horizontal Velocity: 250 m/s, 
                            # Max Vertical Velocity: 100 m/s
fix_mode: 3d                # 1: 2d, 2: 3d, 3: auto
enable_ppp: false

uart1:
  baudrate: 115200
  in: 16                     # RTCM 3
  out: 16                    # No UART out for rover

gnss:
  gps: true
  glonass: false
  beidou: false
  qzss: false
  sbas: true

sbas:
  max: 2   # obsolete
  usage: 7 # bit0: range, bit1: differential corrections, bit2: integrity
  
#dgnss_mode: 3               # Fixed mode

inf: 
  all: true                 # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  nav:
      all: true
#  rxm:
#      all: true # not supported ?
  esf: true
#  aid:
#      all: true
#  mon:
#      all: true
#    hui: false
#  nav:
#    posecef: false
